# Makefile for the ROOT test programs.
# This Makefile shows nicely how to compile and link applications
# using the ROOT libraries on all supported platforms.
prot:
	make -f makefile.prot

pim:
	make -f makefile.pim

pip:
	make -f makefile.pip
